### ISSUE TITLE
Crash at the end of a quiz

### ISSUE THREAD

**Issue by saluf** [saluf/android-kakikana#5]
App crashes at the end of quiz (uploading result)

Stack trace:
```
2020-10-18 10:49:35.693 10438-10438/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.salab.project.kakikana, PID: 10438
    java.lang.IllegalStateException: Fragment ProfileFragment{fc1ed15} (f05f448d-d226-467d-b1c9-2d31818712ed)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
        at com.salab.project.kakikana.ui.ProfileFragment.setupUI(ProfileFragment.java:76)
        at com.salab.project.kakikana.ui.ProfileFragment.lambda$onViewCreated$0$ProfileFragment(ProfileFragment.java:60)
        at com.salab.project.kakikana.ui.-$$Lambda$ProfileFragment$nzEoxayS9zvs4NoN3S7xZoHjWpo.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at com.salab.project.kakikana.viewmodel.FirebaseQueryLiveData.access$100(FirebaseQueryLiveData.java:22)
        at com.salab.project.kakikana.viewmodel.FirebaseQueryLiveData$CustomValueEventListener.onDataChange(FirebaseQueryLiveData.java:72)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
        at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

Trace result:
```
//ProfileFragment
 private void setupUI(User user) {
       //...
       DateFormat simpleFormat = android.text.format.DateFormat.getMediumDateFormat(requireContext());

}
```
```
// ProfileFragment
    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        //...
        userViewModel.getUserData().observe(requireActivity(), dataSnapshot -> {
            if (dataSnapshot != null){
                User user = dataSnapshot.getValue(User.class);
                if (user != null) {setupUI(user);} //<--
            }
        });
    }
```
```
// FirebaseQueryLiveData
    private class CustomValueEventListener implements ValueEventListener {
        @Override
        public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
            setValue(dataSnapshot); // LiveData.setValue() to notify all observers

        }
```

**Comment by saluf** [comment]
Tests:
- Login Anonymously : OK!
- Link with Google (first) : Crash!
- Link with Google (re-launch) : OK!
- Login with Google (first) : Crash!
- Login with Google (re-launch): OK!
